on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Build index.html file
              run: python build.py

            - name: Upload built files
              uses: actions/upload-pages-artifact@v3
              with: 
                path: out/

    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: build
        permissions:
            pages: write
            id-token: write
        steps:
            - name: Deplou to Github Pages
              uses: actions/deploy-pages@v4

    createPullRequest:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Make changes to pull request
          run: date +%s > report.txt

        - name: Create Pull Request
          id: cpr
          uses: peter-evans/create-pull-request@v7
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Update report
            committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
            author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
            signoff: false
            branch: example-patches
            delete-branch: true
            title: '[Example] Update report'
            body: |
              Update report
              - Updated with *today's* date
              - Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
            labels: |
              report
              automated pr
            assignees: peter-evans
            reviewers: peter-evans
            team-reviewers: |
              developers
              qa-team
            milestone: 1
            draft: false